name: Auth Service CI

on:
  push:
    branches: 
      - k8s 
    paths:
      - "projects/boutique-microservices/backend/services/auth/**"
      - ".github/workflows/auth-ci.yml"
      
env:
  WORKING_DIR: projects/boutique-microservices/backend/services/auth
      
jobs:
  code-test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: NodeJS Setup
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install Dependencies
        working-directory: ${{env.WORKING_DIR}}
        run: |
          npm install
          npm run build --if-present
          
  credentials-security-scanning:
    runs-on: ubuntu-latest
    needs: code-test-and-build
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Creadentials HardCoding Scanning
        uses: gitleaks/gitleaks-action@v2
        env: 
          GITHUB_TOKEN: ${{secrets.GAT}}
          
  docker-build-and-scan:
    runs-on: ubuntu-latest
    needs: credentials-security-scanning
    steps:
      - name: Code Checkout 
        uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_ACCESS_TOKENS}}
      - name: Docker BuildX Setup
        uses: docker/setup-buildx-action@v3
      - name: Docker Image Build
        uses: docker/build-push-action@v5
        with:
          context: ${{env.WORKING_DIR}}
          load: true
          tags: boutique-auth:${{github.sha}}
      - name: Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'boutique-auth:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
      - name: Software Bill of Material
        uses: anchore/sbom-action@v0
        with: 
          format: spdx-json
          output-file: sbom.spdx.json
      - name: Uploading SBOM artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: software-bill-of-material-of-auth
          path: sbom.spdx.json
      - name: Push To DockerHub
        run: |
          docker tag boutique-auth:${{github.sha}} ${{secrets.DOCKER_USERNAME}}/boutique-auth:${{github.sha}}
          docker push ${{secrets.DOCKER_USERNAME}}/boutique-auth:${{github.sha}}
  kubernetes-deployment:
    needs: docker-build-and-scan
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      
      - name: Kubernetes Configurations & image Rollout
        run: |
           mkdir -p ~/.kube
           echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
           chmod 600 ~/.kube/config
           kubectl set image deployment/boutique-auth-deployment boutique-auth=${{secrets.DOCKER_USERNAME}}/boutique-auth:${{github.sha}} -n boutique
           kubectl rollout status deployment/boutique-auth-deployment -n boutique 